[package]
name = "noir_rsa_optimised"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
num-bigint = "0.4.4"
num-traits = "0.2.17"
rand = "0.8.5"
rsa = { version = "0.9.6", features = ["sha2"] }
sha256 = "1.4.0"
