[package]
name = "noir_rsa_optimised"
type = "bin"
authors = ["michaelelliot"]
compiler_version = ">=0.19.0"

[dependencies]
large_integer = { tag = "0.1.0", git = "https://github.com/madztheo/noir-large-integer", directory = "crates/large-integer-64" }
rsa = { path = "./crates/rsa" }
